### ISSUE TITLE
Can this library be used with JS or React Native?

### ISSUE THREAD

**Issue by georgeMorales** [chintan369/Geo-FireStore-Query#11]
I am using geofirestore in my project, with react native and firebase firestore for geospatial queries but I cannot paginate the data when using geohash. I have seen this library and I don't know if I could use it.
I have been looking for a solution for a while to be able to scale my application when I ask a question and there is a lot of response data.
Any advice or other bookstore or technology that I can use to get paging would help me a lot.
Thank you!

**Comment by cbarrios** [comment]
Hi is this library only for Kotlin? What about Java?

**Comment by chintan369** [comment]
@georgeMorales This library is right now only for native android.
and @cbarrios this library is working with both java and Kotlin but `setLocation()` function is to be made java compatible. Once this will be done I will update library and inform you.
